### ISSUE TITLE
Scatterplot: Sonification does not work

### ISSUE THREAD

**Issue by jooyoungseo** [uiuc-ischool-accessible-computing-lab/r_maidr#4]
@ellvix and @sandeep-ps 

I have produced the following scatterplot test via maidr R binder. FYI, I bundled the latest upstream maidr js and css. Unfortunately, sonification is not working at all: https://github.com/uiuc-ischool-accessible-computing-lab/r_maidr/blob/f12820d3d0ffd998ee9f6a2ecb42ec3fa8dafc1f/test/scatterplot_test

Could you please help me debug and fix the issue in the upstream maidr branch?

## Repros

``` r
# Install maidr R binder in your R console:
install.packages("remotes")
remotes::install_github("uiuc-ischool-accessible-computing-lab/r_maidr")

# Create sample scatterplot
library(maidr)
library(tidyverse)

g <- ggplot(starwars, aes(height, mass)) +
  geom_point() +
  geom_smooth()

  # Make it accessible via maidr
maidr(g)
```

**Comment by sandeep-ps** [comment]
I see that this is using Maider 0.9.0, but the most recent version in npm is 1.0.3. I'm unsure if this has any connection, but I thought of sharing anyway.  Thanks.

**Comment by jooyoungseo** [comment]
@sandeep-ps -- Actually, I forgot to increase the version number in the folder name in R binder; however, the actual file content used in this example is the up-to-date maidr v1.0.3. So, this should not be the cause of the issue.

@ellvix -- Could you please take a look at this issue at your earliest convenience? This is a high prioirity because the R binder is not working at all due to this issue. FYI, you don't need to install or test any R package. Just please use the html file that I created and mentioned in the body. Many thanks!

**Comment by sandeep-ps** [comment]
Hi, @jooyoungseo, 

Sean and I had a good debugging session today. He did most of the debugging while I watched and provided some input as I encountered things. I will create another GitHub issue in the maidr repo as part of the fix needs to be done there.
